CamNum = 2

[Cam0]
SensorPad = 0
ResIndex = 1

VifDev = 0
HDR = 0
WorkMode = 0
#1Multi=0, 2Multi=1, 4Multi=2

IspDevId = 0
IspChnId = 0
IspbindType = 1
#Frame=0x1, Realtime=0x4
IspBin = /bootconfig/iqfile/isp_api.bin
NRLevel = 1
IspOutPort0 = 1

SclNum = 5

Scl0Dev = 0
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl0DevUseSclId = 0x13
Scl0Chn = 0

Scl0HWScl0 = 1
Scl0HWScl0W = 3840
Scl0HWScl0H = 2160
Scl0HWScl0Pixel = 11
Scl0HWScl0userdepth = 0
Scl0HWScl0depth = 3
Scl0HWScl1 = 1
Scl0HWScl1W = 640
Scl0HWScl1H = 360
Scl0HWScl1Pixel = 11
Scl0HWScl1userdepth = 0
Scl0HWScl1depth = 4
Scl0HWScl4 = 1
Scl0HWScl4W = 1920
Scl0HWScl4H = 1080
Scl0HWScl4Pixel = 11
Scl0HWScl4userdepth = 0
Scl0HWScl4depth = 3

Scl1Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl1InBindMod = 34
Scl1InBindDev = 3
Scl1InBindChn = 8
Scl1InBindPort = 0
Scl1DevUseSclId = 0x20
Scl1Chn = 3
Scl1HWScl5 = 1
Scl1HWScl5W = 432
Scl1HWScl5H = 240
Scl1HWScl5Pixel = 11
Scl1HWScl5userdepth = 1
Scl1HWScl5depth = 4

Scl2Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl2InBindMod = 34
Scl2InBindDev = 0
Scl2InBindChn = 0
Scl2InBindPort = 1
Scl2DevUseSclId = 0x20
Scl2Chn = 4
Scl2HWScl5 = 1
Scl2HWScl5W = 160
Scl2HWScl5H = 90
Scl2HWScl5Pixel = 11
Scl2HWScl5userdepth = 1
Scl2HWScl5depth = 4

Scl3Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl3InBindMod = 34
Scl3InBindDev = 3
Scl3InBindChn = 8
Scl3InBindPort = 0
Scl3DevUseSclId = 0x20
Scl3Chn = 5
Scl3HWScl5 = 1
Scl3HWScl5W = 256
Scl3HWScl5H = 144
Scl3HWScl5Pixel = 11
Scl3HWScl5userdepth = 1
Scl3HWScl5depth = 4

Scl4Dev = 3
#is_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl4InBindMod = 34
Scl4InBindDev = 0
Scl4InBindChn = 0
Scl4InBindPort = 1
Scl4DevUseSclId = 0x20
Scl4Chn = 8
Scl4HWScl5 = 1
Scl4HWScl5W = 640
Scl4HWScl5H = 360
Scl4HWScl5Pixel = 11
Scl4HWScl5userdepth = 1
Scl4HWScl5depth = 4


VencNum = 5

Venc0Chn = 0
Venc0Type = 0
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc0Codec = 1
#h264=0, h265=1, jpeg=2
Venc0BitRate = 30000000
#Venc0BufSize = 2400000
#Venc0InBindType = 16
Venc0InBindMod = 34
Venc0InBindDev = 0
Venc0InBindChn = 0
Venc0InBindPort = 0

Venc1Chn = 1
Venc1Type = 4
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc1Codec = 0
#h264=0, h265=1, jpeg=2
Venc1BitRate = 8000000
Venc1InBindMod = 34
Venc1InBindDev = 0
Venc1InBindChn = 0
Venc1InBindPort = 2
Venc1MaxW = 2048
Venc1MaxH = 2048

Venc2Chn = 2
Venc2Type = 2
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc2Codec = 2
#h264=0, h265=1, jpeg=2
Venc2MaxW = 2048
Venc2MaxH = 2048
Venc2InBindMod = 34
Venc2InBindDev = 0
Venc2InBindChn = 0
Venc2InBindPort = 2

#Venc3Chn = 3
#Venc3Type = 1
##rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
#Venc3Codec = 0
##h264=0, h265=1, jpeg=2
#Venc3BitRate = 800000
##Venc3BufSize = 77000
#Venc3InBindMod = 34
#Venc3InBindDev = 0
#Venc3InBindChn = 0
#Venc3InBindPort = 1

Venc3Chn = 4
Venc3Type = 5
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc3Codec = 2
#h264=0, h265=1, jpeg=2
Venc3MaxW = 720
Venc3MaxH = 720
Venc3InBindMod = 34
Venc3InBindDev = 3
Venc3InBindChn = 5
Venc3InBindPort = 0

Venc4Chn = 5
Venc4Type = 7
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc4Codec = 2
#h264=0, h265=1, jpeg=2
Venc4BitRate = 2000000
Venc4MaxW = 720
Venc4MaxH = 720
Venc4InBindMod = 34
Venc4InBindDev = 3
Venc4InBindChn = 8
Venc4InBindPort = 0

MuxNum = 1

Mux0Chn = 0
Mux0TrakNum = 1
Mux0Trak0Venc = 0
Mux0Type = 0
#normal=0, emerg=1, share=2
Mux0File = 0
#main stream file=0, sub stream file=1
Mux0Thumb = 1

Mux1Chn = 1
Mux1TrakNum = 1
Mux1Trak0Venc = 0
Mux1Type = 1
#normal=0, emerg=1, share=2
Mux1File = 0
#main stream file=0, sub stream file=1
Mux1Thumb = 1

[Cam1]
SensorPad = 3
ResIndex = 0
AnadecW = 1920
AnadecH = 1080
AnadecFps = 25
AnadecMode = 3 # CVI=1, TVI=2, AHD=3

VifDev = 12
HDR = 0
WorkMode = 2
#1Multi=0, 2Multi=1, 4Multi=2

SclNum = 5

Scl0Dev = 2
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl0DevUseSclId = 0x0c
Scl0Chn = 0
Scl0HWScl2 = 1
Scl0HWScl2W = 1920
Scl0HWScl2H = 1080
Scl0HWScl2Pixel = 11
Scl0HWScl2userdepth = 0
Scl0HWScl2depth = 4
Scl0HWScl3 = 1
Scl0HWScl3W = 640
Scl0HWScl3H = 360
Scl0HWScl3Pixel = 11
Scl0HWScl3userdepth = 0
Scl0HWScl3depth = 4

Scl1Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl1InBindMod = 34
Scl1InBindDev = 2
Scl1InBindChn = 0
Scl1InBindPort = 1
Scl1DevUseSclId = 0x20
Scl1Chn = 6
Scl1HWScl5 = 1
Scl1HWScl5W = 160
Scl1HWScl5H = 90
Scl1HWScl5Pixel = 11
Scl1HWScl5userdepth = 0
Scl1HWScl5depth = 4

Scl2Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl2InBindMod = 34
Scl2InBindDev = 2
Scl2InBindChn = 0
Scl2InBindPort = 0
Scl2DevUseSclId = 0x20
Scl2Chn = 7
Scl2HWScl5 = 1
Scl2HWScl5W = 256
Scl2HWScl5H = 144
Scl2HWScl5Pixel = 11
Scl2HWScl5userdepth = 0
Scl2HWScl5depth = 4

Scl3Dev = 3
#is_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl3InBindMod = 34
Scl3InBindDev = 2
Scl3InBindChn = 0
Scl3InBindPort = 1
Scl3DevUseSclId = 0x20
Scl3Chn = 9
Scl3HWScl5 = 1
Scl3HWScl5W = 640
Scl3HWScl5H = 360
Scl3HWScl5Pixel = 11
Scl3HWScl5userdepth = 1
Scl3HWScl5depth = 4

Scl4Dev = 3
#is_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl4InBindMod = 34
Scl4InBindDev = 2
Scl4InBindChn = 0
Scl4InBindPort = 0
Scl4DevUseSclId = 0x20
Scl4Chn = 10
Scl4HWScl5 = 1
Scl4HWScl5W = 1920
Scl4HWScl5H = 1080
Scl4HWScl5Pixel = 11
Scl4HWScl5userdepth = 0
Scl4HWScl5depth = 4

VencNum = 4

Venc0Chn = 6
Venc0Type = 0
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc0Codec = 1
#h264=0, h265=1, jpeg=2
Venc0BitRate = 10000000
#Venc0BufSize = 700000
Venc0InBindMod = 34
Venc0InBindDev = 3
Venc0InBindChn = 10
Venc0InBindPort = 0
Venc0MaxW = 2048
Venc0MaxH = 2048

Venc1Chn = 7
Venc1Type = 2
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc1Codec = 2
#h264=0, h265=1, jpeg=2
Venc1MaxW = 2048
Venc1MaxH = 2048
Venc1InBindMod = 34
Venc1InBindDev = 3
Venc1InBindChn = 10
Venc1InBindPort = 0

#Venc2Chn = 8
#Venc2Type = 1
##rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
#Venc2Codec = 0
##h264=0, h265=1, jpeg=2
#Venc2BitRate = 800000
##Venc2BufSize = 77000
#Venc2InBindMod = 34
#Venc2InBindDev = 2
#Venc2InBindChn = 0
#Venc2InBindPort = 1

Venc2Chn = 9
Venc2Type = 5
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc2Codec = 2
#h264=0, h265=1, jpeg=2
Venc2MaxW = 720
Venc2MaxH = 720
Venc2InBindMod = 34
Venc2InBindDev = 3
Venc2InBindChn = 7
Venc2InBindPort = 0

Venc3Chn = 10
Venc3Type = 7
#rec=0, subrec=1, cap=2, rtsp=3, uvc=4, thumb=5, share=6, user=7
Venc3Codec = 2
#h264=0, h265=1, jpeg=2
Venc3MaxW = 720
Venc3MaxH = 720
Venc3BitRate = 2000000
Venc3InBindMod = 34
Venc3InBindDev = 3
Venc3InBindChn = 9
Venc3InBindPort = 0

MuxNum = 1

Mux0Chn = 2
Mux0TrakNum = 1
Mux0Trak0Venc = 6
Mux0Type = 0
#normal=0, emerg=1, share=2
Mux0File = 0
#main stream file=0, sub stream file=1
Mux0Thumb = 1

Mux1Chn = 3
Mux1TrakNum = 1
Mux1Trak0Venc = 6
Mux1Type = 1
#normal=0, emerg=1, share=2
Mux1File = 0
#main stream file=0, sub stream file=1
Mux1Thumb = 1

[OSD]

Attach0Mod = 34
Attach0Dev = 0
Attach0Chn = 0
Attach0Port = 0
Attach0Mirror = 0

Attach1Mod = 34
Attach1Dev = 0
Attach1Chn = 0
Attach1Port = 2
Attach1Mirror = 0

Attach2Mod = 34
Attach2Dev = 3
Attach2Chn = 10
Attach2Port = 0
Attach2Mirror = 0

Attach3Mod = 34
Attach3Dev = 3
Attach3Chn = 8
Attach3Port = 0
Attach3Mirror = 0

Attach4Mod = 34
Attach4Dev = 3
Attach4Chn = 9
Attach4Port = 0
Attach4Mirror = 0


[Disp]

SclNum = 3

Scl0Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl0DevUseSclId = 0x20
Scl0Chn = 0
Scl0Rot = 1
#none=0, rot90=1, rot180=2, rot270=3
Scl0HWScl5 = 1
Scl0HWScl5W = 360
Scl0HWScl5H = 640
Scl0HWScl5Pixel = 11
Scl0HWScl5userdepth = 0
Scl0HWScl5depth = 4

Scl1Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl1DevUseSclId = 0x20
Scl1Chn = 1
Scl1Rot = 1
#none=0, rot90=1, rot180=2, rot270=3
Scl1HWScl5 = 1
Scl1HWScl5W = 90
Scl1HWScl5H = 160
Scl1HWScl5Pixel = 11
Scl1HWScl5userdepth = 0
Scl1HWScl5depth = 4


Scl2Dev = 3
#isp_realtime=dev0, rdma0=dev1, yuv_realtime=dev2, rdma1=dev3, rdma_rot=dev3
Scl2DevUseSclId = 0x20
Scl2Chn = 2
Scl2HWScl5 = 1
Scl2HWScl5W = 640
Scl2HWScl5H = 360
Scl2HWScl5Pixel = 11
Scl2HWScl5userdepth = 0
Scl2HWScl5depth = 4


Dev0 = 1
Dev0IntfType = MIPI
Dev0IntfSync = user

Dev0Layer0 = 1
Dev0Layer0WinW = 360
Dev0Layer0WinH = 640
Dev0Layer0WinX = 0
Dev0Layer0WinY = 0
Dev0Layer0W = 360
Dev0Layer0H = 640

Dev0Layer0Port0 = 1
Dev0Layer0Port0X = 0
Dev0Layer0Port0Y = 0
Dev0Layer0Port0W = 360
Dev0Layer0Port0H = 640
Dev0Layer0Port0SrcW = 360
Dev0Layer0Port0SrcH = 640
Dev0Layer0Port0InMod = 34
Dev0Layer0Port0InDev = 3
Dev0Layer0Port0InChn = 0
Dev0Layer0Port0InPort = 0

Dev0Layer1 = 1
Dev0Layer1WinW = 90
Dev0Layer1WinH = 160
Dev0Layer1WinX = 0
Dev0Layer1WinY = 0
Dev0Layer1W = 90
Dev0Layer1H = 160

Dev0Layer1Port0 = 1
Dev0Layer1Port0X = 230
Dev0Layer1Port0Y = 470
Dev0Layer1Port0W = 90
Dev0Layer1Port0H = 160
Dev0Layer1Port0srcW = 90
Dev0Layer1Port0srcH = 160
Dev0Layer1Port0InMod = 34
Dev0Layer1Port0InDev = 3
Dev0Layer1Port0InChn = 1
Dev0Layer1Port0InPort = 0

#Cam0 Full
Bind0SrcMod = 34
Bind0SrcDev = 0
Bind0SrcChn = 0
Bind0SrcPort = 1
Bind0DstMod = 34
Bind0DstDev = 3
Bind0DstChn = 0
Bind0DstPort = 0

#Cam0 PIP
Bind1SrcMod = 34
Bind1SrcDev = 3
Bind1SrcChn = 4
Bind1SrcPort = 0
Bind1DstMod = 34
Bind1DstDev = 3
Bind1DstChn = 1
Bind1DstPort = 0

#Cam1 Full
Bind2SrcMod = 34
Bind2SrcDev = 2
Bind2SrcChn = 0
Bind2SrcPort = 1
Bind2DstMod = 34
Bind2DstDev = 3
Bind2DstChn = 0
Bind2DstPort = 0

#Cam1 PIP
Bind3SrcMod = 34
Bind3SrcDev = 3
Bind3SrcChn = 6
Bind3SrcPort = 0
Bind3DstMod = 34
Bind3DstDev = 3
Bind3DstChn = 1
Bind3DstPort = 0


BindMapNum = 4
BindMap0 = 0x9 #Cam0 Full + Cam1 PIP
BindMap1 = 0x6 #Cam0 PIP + Cam1 Full
BindMap2 = 0x1 #Cam0 Full
BindMap3 = 0x4 #Cam1 Full

#playback
Bind0PBSrcMod = 34
Bind0PBSrcDev = 3
Bind0PBSrcChn = 2
Bind0PBSrcPort = 0
Bind0PBDstMod = 34
Bind0PBDstDev = 3
Bind0PBDstChn = 0
Bind0PBDstPort = 0

BindPBMapNum = 1

[VDF]
Chn0 = 1
Chn0SrcMod = 34
Chn0SrcDev = 3
Chn0SrcChn = 3
Chn0SrcPort = 0

Chn1 = 1
Chn1SrcMod = 34
Chn1SrcDev = 3
Chn1SrcChn = 7
Chn1SrcPort = 0
